---
title: "data import"
output: github_document
---

This file is for doing data import.

# import csv
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

import the first dataset

```{r}
litter_df=
  read_csv(file="data_import_examples/data_import_examples/FAS_litters.csv", na = c(".", "NA",""))
litter_df=janitor::clean_names(litter_df)
```

import the second dataset

```{r}
pups_df=
  read_csv(file="data_import_examples/data_import_examples/FAS_pups.csv",skip=3, na = c(".", "NA",""), col_types = "fddddd")
pups_df=janitor::clean_names(pups_df)
```
head or tail
```{r}
head(pups_df,5)
tail(pups_df,5)
```

skimming
```{r}
skimr::skim(pups_df)
```
#import excel
```{r}
mlb_df=
  read_excel("data_import_examples/data_import_examples/mlb11.xlsx")
```
import FORT words
```{r}
fotr_df=
  read_excel(
    "data_import_examples/data_import_examples/LotR_Words.xlsx",
    range="F3:H6"#单元格表示法（只读取这部分的）
  )
```

#import sas
```{r}
pulse_df=
  read_sas("data_import_examples/data_import_examples/public_pulse_data.sas7bdat")

pulse_df=janitor::clean_names(pulse_df)
```

##what's so bad about 'read_csv()'
```{r}
pups_df_base=
  read.csv("data_import_examples/data_import_examples/FAS_pups.csv")
```
lazy about variable names(conflicts on variable names) and super slow for big datasets

